FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY . .
WORKDIR /src/src/Miningcore
RUN dotnet publish -c Release -p:BUILD_NATIVE_LIBS=false -o /out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /out/ ./
ENTRYPOINT ["dotnet","Miningcore.dll","-c","/config/config.json"]
